spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  username: sell
  password: 12345
  url: jdbc:mysql://localhost:3306/order_system?characterEncoding=utf-8&useSSL=false
 jpa:
  show-sql: true
server:
  context-path: /sell





